name: dartsand
description: Project for testing sample Dart code via the Dart command line
version: 1.0.0

publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
